[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]
[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.75
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14
